name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2025]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Compute node modules cache key
        id: nodeModulesCacheKey
        run: echo "value=$(node packages/build/src/computeNodeModulesCacheKey.ts)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v6
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cacheNodeModules-${{ steps.nodeModulesCacheKey.outputs.value }}
      - name: npm ci
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm run build
      - run: npm run build:static
      - run: npm test
      - run: npm run type-check
      - run: npm run lint
      - name: Install Playwright dependencies
        working-directory: ./packages/e2e
        run: npx playwright install chromium
        if: steps.npm-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: Install OpenSSH server
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt-get update && sudo apt-get install --yes openssh-server
      - name: Run headless test
        if: matrix.os != 'windows-2025'
        run: npm run e2e:headless
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: Run browser-only SSH test
        if: matrix.os == 'ubuntu-24.04'
        run: npm run e2e:iwa
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: Upload artifact
        if: matrix.os == 'ubuntu-24.04'
        uses: actions/upload-artifact@v7
        with:
          name: remote-ssh-extension
          path: extension.tar.br
